10     !nombre de pas/maille du cylindre selon x
1      !Rayon[m]
0.5    !débit [m3/s]
1000   !rho[kg/m3]
1000   !Capacité calorifique [J/kgK]
10     !Conductivité thermique dans le tube [W/(m.K)]
1      !Conductivité thermique dans l'epaisseur [W/(m.K)]
273    !Température initiale du cylindre[K]
350    !Tinfini [K]
10     !h extérieur [W/m2.K]
100    !h intérieur [W/m2.K]
5      !longueur du cylindre [m]
0.1    !epaisseur [m]
10     !Nombre de pas de temps [s]
1000   !durée [s]
100    !Temps de sauvegarde [s]
